// <auto-generated />
using System;
using DatabaseOpgave2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MovieDB.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20231101110703_DBSetUp")]
    partial class DBSetUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Obligatorisk_Database.Models.NameBasics", b =>
                {
                    b.Property<string>("NConst")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<int>("DeathYear")
                        .HasColumnType("int");

                    b.Property<string>("KnownForTitles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryProfession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NConst");

                    b.ToTable("NameBasics");
                });

            modelBuilder.Entity("Obligatorisk_Database.Models.TitleBasics", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdult")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RuntimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TConst");

                    b.ToTable("TitleBasics");
                });

            modelBuilder.Entity("Obligatorisk_Database.Models.TitleCrew", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Directors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Writers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TConst");

                    b.ToTable("TitleCrew");
                });
#pragma warning restore 612, 618
        }
    }
}
